### ISSUE TITLE
Pairs BTC/USDT and BTC/USDT from Kraken not available through Cryptostore?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#101]
Hi,

I tried to retrieve following data for following pairs from Kraken.

```yaml
exchanges:
    KRAKEN:
        channel_timeouts:
            trades: 90
        retries: 6
        trades: [BTC-USDT,ETH-USDT]
```
Both of them throw this error:
```bash
Process Collector-1:1:
Traceback (most recent call last):
  File "/home/pierre/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/cryptostore-0.3.1-py3.7.egg/cryptostore/collector.py", line 113, in run
    fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 109, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/kraken.py", line 25, in __init__
    super().__init__('wss://ws.kraken.com', pairs=pairs, channels=channels, callbacks=callbacks, **kwargs)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 44, in __init__
    self.config[chan].update([pair_std_to_exchange(pair, self.id) for pair in config[channel]])
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 44, in <listcomp>
    self.config[chan].update([pair_std_to_exchange(pair, self.id) for pair in config[channel]])
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/standards.py", line 58, in pair_std_to_exchange
    raise UnsupportedTradingPair(f'{pair} is not supported on {exchange}')
cryptofeed.exceptions.UnsupportedTradingPair: ETH-USDT is not supported on KRAKEN
```

However, checking directly on Kraken website, these pairs are both available for trading.
Please, what is wrong?
Thanks for your support.
Bests

**Comment by yohplala** [comment]
I can confirm I tested other paris like `ETH/USD` and `BTC/USD`, both of them work.

**Comment by bmoscon** [comment]
fixed

**Comment by yohplala** [comment]
@bmoscon Bryant, you are terrific! 👍
