### ISSUE TITLE
Wrong error message with OKEX: 'open_interest' probably not available, says 'ticker_swap' is unknown instead.

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#103]
Hi,

Trying following config. with OKEX raises below error message.
```yaml
exchanges:
    OKEX:
        channel_timeouts:
            open_interest: 90
        retries: 6
        open_interest: [BTC-USD-SWAP]
```
Error message:
```bash
2020-08-21 22:32:40,716 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 213, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 242, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 163, in message_handler
    await self._ticker(msg, timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 70, in _ticker
    receipt_timestamp=timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 129, in callback
    for cb in self.callbacks[data_type]:
KeyError: 'ticker_swap'
```

A `KeyError:'ticker_swap'` is definitely surprising at this time when I am only requesting `open_interest`.

Bests

**Comment by yohplala** [comment]
I confirm, problem is solved, and `open_interest` is actually available!
