### ISSUE TITLE
Redis error on stock install, ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jeffneuen** [bmoscon/cryptostore#12]
I have installed cryptostore from master, updated as of the date of this issue filing, and installed via "python setup.py install".

When I attempt to run "cryptostore", using the provided sample config.yaml, I get an error related to Redis. I did have to install Redis manually using apt-update install. I have verified that Redis is working using Redis-cli on 127.0.0.1. The version of Redis that 18.04 LTS currently installs is 5:4.0.9. I am also running Anaconda, a virtualenv configured with python 3.7.

The error message I get pasted below, and it just repeats over and over as new events are received. My first thought was that ubuntu was using an old version of Redis that didn't support streams and XADD, but that doesn't seem to be the case. 

Any ideas on what to try next are appreciated.

```
2019-05-10 17:49:09,540 : ERROR : COINBASE: error handling message {"type":"last_match","trade_id":63297970,"maker_order_id":"2ff0f4fc-f0d3-4882-b111-a9734a59497d","taker_order_id":"ce5a3f03-ef73-4b4f-8c36-a45a5f194b21","side":"buy","size":"0.02889234","price":"6394.99000000","product_id":"BTC-USD","sequence":9408705355,"time":"2019-05-10T17:49:08.476000Z"}
2019-05-10 17:49:09,571 : ERROR : COINBASE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/root/anaconda3/envs/cryptostore/lib/python3.7/site-packages/cryptofeed-0.22.1-py3.7.egg/cryptofeed/feedhandler.py", line 166, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/root/anaconda3/envs/cryptostore/lib/python3.7/site-packages/cryptofeed-0.22.1-py3.7.egg/cryptofeed/feedhandler.py", line 184, in _handler
    await handler(message)
  File "/root/anaconda3/envs/cryptostore/lib/python3.7/site-packages/cryptofeed-0.22.1-py3.7.egg/cryptofeed/coinbase/coinbase.py", line 279, in message_handler
    await self._book_update(msg)
  File "/root/anaconda3/envs/cryptostore/lib/python3.7/site-packages/cryptofeed-0.22.1-py3.7.egg/cryptofeed/coinbase/coinbase.py", line 123, in _book_update
    timestamp=timestamp_normalize(self.id, msg['time'])
  File "/root/anaconda3/envs/cryptostore/lib/python3.7/site-packages/cryptofeed-0.22.1-py3.7.egg/cryptofeed/backends/redis.py", line 56, in __call__
    await self.redis.xadd(f"{self.key}-{feed}-{pair}", data)
aioredis.errors.ReplyError: ERR unknown command 'XADD'
```

**Comment by bmoscon** [comment]
What is your output from pip freeze?

I did a clean install in a new virtualenv (just ran `pip install cryptostore[arctic]`) and it worked as expected. My guess is an outdated version of aioredis/redis?

here is my pip freeze output

```
aiodns==2.0.0
aiohttp==3.5.4
aioredis==1.2.0
arctic==1.79.1
async-timeout==3.0.1
attrs==19.1.0
cchardet==2.1.4
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cryptofeed==0.22.0
cryptostore==0.0.5
decorator==4.4.0
enum-compat==0.0.2
futures==3.1.1
hiredis==1.0.0
idna==2.8
lz4==2.1.6
mockextras==1.0.2
multidict==4.5.2
numpy==1.16.3
pandas==0.24.2
pyarrow==0.13.0
pycares==3.0.0
pycparser==2.19
pymongo==3.8.0
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1
redis==3.2.1
requests==2.21.0
six==1.12.0
sortedcontainers==2.1.0
tzlocal==1.5.1
urllib3==1.24.3
websockets==7.0
yarl==1.3.0
```

**Comment by bmoscon** [comment]
also @jeffneuen ubuntu's versioning isnt 100% clear to me, so I'm not positive what `5:4.0.9` maps to, but if its less than 5.0, it wont work, redis streams were introduced in redis 5.0. I'm guessing its version 4.0.9, so you may need to install redis from a different PPA or from source, or wait a few days until I release the kafka cache for cryptostore

**Comment by jeffneuen** [comment]
I agree, ubuntu's Redis versioning is weird.

I made a new virtualenv and installed again via pip install cryptostore[arctic] . I also installed Redis from a PPA, so now I get

Redis server v=5.0.4 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=6840e401a1a58e85

My pip freeze has aioredis==1.2.0. 

Still the same error, very weird.

I can wait for Kafka though, that's what I'd rather use anyway. Thanks!

**Comment by bmoscon** [comment]
kafka support is released so I'm going to close this out. I've also made it clearer in the documentation that Redis 5.0+ is required if redis is being used

**Comment by xiandong79** [comment]
@jeffneuen you should update/upgrade your Redis. 
I also got "ERR unknown command 'XADD'" when I use old version Redis-server.

you can search "ubuntu install latest redis" in google.com

**Comment by nskforward** [comment]
redis:5.0.6-alpine
ERR unknown command `XADD mystream * sensor-id 1234 temperature 19.8`, with args beginning with:
