### ISSUE TITLE
Redis RDB snapshots

### ISSUE THREAD

**Issue by JayCooper95** [bmoscon/cryptostore#121]
Cryptostore was configured to save Binance and Coinbase L2 and trade data to parquet files every 10 minutes (storage_interval will be increased in prod this was only done as a test). Run using Redis and after 3 days of running the following error message occurred.

2020-10-15 16:41:06,586 : ERROR : Aggregator running on PID 3467 died due to exception
Traceback (most recent call last):
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 98, in loop
    cache.delete(exchange, dtype, pair)
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/cryptostore/aggregator/redis.py", line 85, in delete
    self.conn.xdel(key, *self.ids[key])
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/redis/client.py", line 2421, in xdel
    return self.execute_command('XDEL', name, *ids)
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/ec2-user/cryptostore/env/lib64/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Operating System:**
 - linux

As I am new to Redis I have not tweaked the configuration file from default settings. I can also upload the Redis logs if needed.

Thanks

**Comment by yohplala** [comment]
Your disk is possibly full.
Disable saving to disk in Redis conf. It just is useless in this use case. (Google Redis, disabling rdb)
Bests,

**Comment by mschneider** [comment]
@JayCooper95 make sure to run redis with the correct configuration. The docker-compose file uses cli args, but you could also just adapt /etc/redis/redis.conf if you are working in a regular installation:

For reference:
https://github.com/bmoscon/cryptostore/blob/master/docker-compose.yml#L21

**Comment by bmoscon** [comment]
if you need more help, let me know
