### ISSUE TITLE
Bug: Crash in L2 book aggregation

### ISSUE THREAD

**Issue by mschneider** [bmoscon/cryptostore#123]
**L2 Book Aggregator is crashing in master**

```
Oct 21 12:57:57 cryptostore docker-compose[1171408]: python-workers_1  | 2020-10-21 12:57:57,819 : INFO : Reading BINANCE-l2_book-ETH-BTC
Oct 21 12:57:57 cryptostore docker-compose[1171408]: python-workers_1  | 2020-10-21 12:57:57,820 : INFO : No data for BINANCE-l2_book-ETH-BTC
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  | 2020-10-21 12:58:57,622 : INFO : Reading BINANCE-l2_book-ETH-BTC
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  | 2020-10-21 12:58:57,626 : INFO : l2_book-BINANCE-ETH-BTC: Read 520 messages from Redis
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  | 2020-10-21 12:58:57,676 : ERROR : Aggregator running on PID 11 died due to exception
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  | Traceback (most recent call last):
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |   File "/usr/local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 108, in loop
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |     store.write(exchange, dtype, pair, time.time())
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |   File "/usr/local/lib/python3.7/site-packages/cryptostore/data/storage.py", line 37, in write
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |     s.write(exchange, data_type, pair, timestamp)
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |   File "/usr/local/lib/python3.7/site-packages/cryptostore/data/arctic.py", line 31, in write
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |     if not self.data:
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 1330, in __nonzero__
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  |     f"The truth value of a {type(self).__name__} is ambiguous. "
Oct 21 12:58:57 cryptostore docker-compose[1171408]: python-workers_1  | ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Example config**

```
redis:
    ip: redis
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

exchanges:
    BINANCE:
        l2_book:
            symbols: [ETH-BTC]
            book_delta: True
            book_interval: 20000

storage: [arctic]

```

**Expected behavior**
- The same configuration was still working a few weeks ago.

**Operating System:**
 - linux / debian

**Cryptofeed Version**
- master

**Comment by bmoscon** [comment]
I think i know the fix for this - let me have a look

**Comment by mschneider** [comment]
thanks! i was just about to look through the diffs..

**Comment by bmoscon** [comment]
I probably wont fix it until evening time in UTC-4, so if you don't care to wait you may want to do that :)
