### ISSUE TITLE
Wrong 'channel_timeouts' used by cryptostore?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#141]
**Describe the bug**
An error reported by cryptostore when receiving no data appears inconsistent with the config file.

config file: requested timeout: 90s
```yaml
# Channel timeouts are channel specific and control how long a channel can go with no messages before declaring the connection
# dead. Cryptofeed will restart the connection if no message is received in this time period. Default is 120 seconds. -1 means no timeout.
    OKEX:
        channel_timeouts:
            trades: 90
            l2_book: 90
        retries: -1
        trades: [USDC-USDT]
        l2_book:
            symbols: [USDC-USDT]
            book_delta: true
            book_interval: 100000
```
(yeah, I know, there certainly are more thrilling pairs to trade with than USDC/USDT on OKEX :) ah ah)

error message
```bash
2020-11-20 07:41:32,408 : WARNING : OKEX: encountered connection issue code = 4001 (private use), reason = no data received in 30s - reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/feedhandler.py", line 258, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/feedhandler.py", line 285, in _handler
    async for message in websocket:
  File "/usr/local/lib/python3.8/dist-packages/websockets-8.1-py3.8-linux-x86_64.egg/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.8/dist-packages/websockets-8.1-py3.8-linux-x86_64.egg/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets-8.1-py3.8-linux-x86_64.egg/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 4001 (private use), reason = no data received in 30s
```

This pair seemingly not very active (omg, how surprising ?! :) ) I have `feedhandler.log` filled with this warning.
No worries, still, why does cryptostore check if data is received every 30s, while default is 120, and in my config file, I asked 90s ?

**To Reproduce**
* Provide config [x]
* redis
* What behavior did you see?    feedhandler.log filled with reported warning
* Provide any tracebacks if applicable [x]

**Expected behavior**
That cryptostore tells me it has no data within 90s, as specified in config file

**Operating System:**
 - Ubuntu 20.04, fresh install on remote server

**Cryptofeed Version**
 - bleeding edge [`WA_over_CG`](https://github.com/yohplala/cryptofeed/tree/WA-over-CG) branch from a as dynamic as mysterious contributor :)

**Comment by bmoscon** [comment]
I fixed this bug in cryptofeed. OKEX expects pings every 30 seconds or it disconnects. cryptofeed did them every 30 seconds, so occasionally it will disconnect. Ive changed the ping rate to 10 seconds.
