### ISSUE TITLE
ImportError: cannot import name 'LiquidationsStream'

### ISSUE THREAD

**Issue by JamesKBowler** [bmoscon/cryptostore#150]
**Describe the bug**

Hello 

When running cryptostore I recieve an import error. Not sure if its a bug or just the way I have installed. 

Thank you
James

**To Reproduce**
```
virtualenv -p /usr/bin/python3.6 /mnt/venv/cryptostore
source /mnt/venv/cryptostore/bin/activate
pip install git+https://github.com/manahl/arctic.git
pip install cryptostore
pip install cryptostore[redis]
pip install zmq
```

* Provide config (at least as much as is relevant)
Changed mongodb url to my remote server and hashed out coinbase, elastic and influx keys in the `config.yml` (log below shows config)

* redis or kafka?
`redis`
* What behavior did you see?

```
(cryptostore) nonroot@pyexe:~$ cryptostore --config /mnt/data/cryptostore/config.yaml 
2021-01-23 16:37:36,090 : INFO : Starting cryptostore
2021-01-23 16:37:36,090 : INFO : Cryptostore running on PID 3703
2021-01-23 16:37:36,092 : INFO : Spawner started
2021-01-23 16:37:36,093 : INFO : Spawner running on PID 3711
2021-01-23 16:37:36,093 : INFO : Aggregator started
2021-01-23 16:37:36,094 : INFO : Aggregator running on PID 3712
2021-01-23 16:37:36,095 : INFO : Cryptostore started
2021-01-23 16:37:36,107 : INFO : start: ['BITMEX'] stop: []
2021-01-23 16:37:36,108 : INFO : message: {"op": "start", "exchange": "BITMEX", "collector": {"channel_timeouts": {"l2_book": 30, "trades": 120, "ticker": 120, "funding": -1}, "retries": -1, "l2_book": {"symbols": ["XBTUSD"], "max_depth": 10, "book_delta": true, "book_interval": 100000}, "trades": ["XBTUSD"], "ticker": ["XBTUSD"], "funding": ["XBTUSD"]}, "config": {"cache": "redis", "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["arctic"], "storage_retries": 5, "storage_retry_wait": 30, "pass_through": {"type": "zmq", "host": "127.0.0.1", "port": 5678}, "parquet": {"del_file": true, "append_counter": 4, "file_format": ["exchange", "pair", "data_type", "timestamp"], "compression": {"codec": "BROTLI", "level": 6}, "path": null, "prefix_date": false, "S3": {"endpoint": null, "key_id": null, "secret": null, "bucket": null, "prefix": null}, "GCS": {"service_account": null, "bucket": null, "prefix": null}, "GD": {"service_account": null, "prefix": null, "folder_name_sep": "."}}, "arctic": "mongodb://192.168.137.21:27017", "storage_interval": 60}}
2021-01-23 16:37:36,109 : INFO : Starting {'op': 'start', 'exchange': 'BITMEX', 'collector': {'channel_timeouts': {'l2_book': 30, 'trades': 120, 'ticker': 120, 'funding': -1}, 'retries': -1, 'l2_book': {'symbols': ['XBTUSD'], 'max_depth': 10, 'book_delta': True, 'book_interval': 100000}, 'trades': ['XBTUSD'], 'ticker': ['XBTUSD'], 'funding': ['XBTUSD']}, 'config': {'cache': 'redis', 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['arctic'], 'storage_retries': 5, 'storage_retry_wait': 30, 'pass_through': {'type': 'zmq', 'host': '127.0.0.1', 'port': 5678}, 'parquet': {'del_file': True, 'append_counter': 4, 'file_format': ['exchange', 'pair', 'data_type', 'timestamp'], 'compression': {'codec': 'BROTLI', 'level': 6}, 'path': None, 'prefix_date': False, 'S3': {'endpoint': None, 'key_id': None, 'secret': None, 'bucket': None, 'prefix': None}, 'GCS': {'service_account': None, 'bucket': None, 'prefix': None}, 'GD': {'service_account': None, 'prefix': None, 'folder_name_sep': '.'}}, 'arctic': 'mongodb://192.168.137.21:27017', 'storage_interval': 60}}
2021-01-23 16:37:36,111 : INFO : Collector for BITMEX running on PID 3714
2021-01-23 16:37:36,224 : INFO : Flushing cache
Process Collector-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/venv/cryptostore/lib/python3.6/site-packages/cryptostore/collector.py", line 60, in run
    from cryptofeed.backends.redis import TradeStream, BookStream, BookDeltaStream, TickerStream, FundingStream, OpenInterestStream, LiquidationsStream
ImportError: cannot import name 'LiquidationsStream'
/mnt/venv/cryptostore/lib/python3.6/site-packages/arctic/_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
2021-01-23 16:37:36,854 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 16:37:36,854 : INFO : No data for BITMEX-l2_book-XBTUSD
2021-01-23 16:37:36,854 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 16:37:36,854 : INFO : No data for BITMEX-trades-XBTUSD
2021-01-23 16:37:36,854 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 16:37:36,855 : INFO : No data for BITMEX-ticker-XBTUSD
2021-01-23 16:37:36,855 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 16:37:36,855 : INFO : No data for BITMEX-funding-XBTUSD
2021-01-23 16:38:36,232 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 16:38:36,233 : INFO : No data for BITMEX-l2_book-XBTUSD
2021-01-23 16:38:36,233 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 16:38:36,233 : INFO : No data for BITMEX-trades-XBTUSD
2021-01-23 16:38:36,233 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 16:38:36,233 : INFO : No data for BITMEX-ticker-XBTUSD
2021-01-23 16:38:36,233 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 16:38:36,233 : INFO : No data for BITMEX-funding-XBTUSD
```

**Expected behavior**
Dunno, its the first time I have used cryptostore

**Operating System:**
 - Linux Ubuntu 20.04

**Cryptofeed Version**
1.4.1

**Comment by bmoscon** [comment]
you posted the cryptostore version, not cryptofeed version

**Comment by JamesKBowler** [comment]
Corrected, Thanks

**Comment by bmoscon** [comment]
that version of cryptofeed is quite old, you should upgrade it.

**Comment by JamesKBowler** [comment]
This cryptofeed version is the last one for python3.6. Also on the Artic ReadMe is says supported versions are `Python 2.7, 3.4, 3.5, 3.6` which is what lead me down the path of Python 3.6.

I did try python 3.8 at first but had issues with imports on Pandas.

`ImportError: cannot import name 'Panel' from 'pandas' (/mnt/venv/cryptostore/lib/python3.8/site-packages/pandas/__init__.py)`

Which python version do you suggest?

**Comment by bmoscon** [comment]
3.7 should work fine. That error above is from arctic, so try downgrading your version of pandas.

**Comment by JamesKBowler** [comment]
3.7 produces the same import error as 3.8, then I followed your advice about the pandas version. The latest version I can get working is `pandas==1.1.5`

`pandas 1.1.5` produces a `FutureWarning` which can be seen in the output below.

Some other warnings too. 

Would you say this is working now? I can see entries in mongodb.

Thanks

```
(cryptostore) nonroot@pyexe:~$ pip install pandas==1.1.5
Collecting pandas==1.1.5
  Downloading pandas-1.1.5-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 2.5 MB/s 
Requirement already satisfied: numpy>=1.15.4 in /mnt/venv/cryptostore/lib/python3.7/site-packages (from pandas==1.1.5) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /mnt/venv/cryptostore/lib/python3.7/site-packages (from pandas==1.1.5) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /mnt/venv/cryptostore/lib/python3.7/site-packages (from pandas==1.1.5) (2020.5)
Requirement already satisfied: six>=1.5 in /mnt/venv/cryptostore/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas==1.1.5) (1.14.0)
Installing collected packages: pandas
Successfully installed pandas-1.1.5
(cryptostore) nonroot@pyexe:~$ cryptostore --config /mnt/data/cryptostore/config.yaml
2021-01-23 20:29:09,827 : INFO : Starting cryptostore
2021-01-23 20:29:09,827 : INFO : Cryptostore running on PID 4515
2021-01-23 20:29:09,829 : INFO : Spawner started
2021-01-23 20:29:09,829 : INFO : Spawner running on PID 4522
2021-01-23 20:29:09,830 : INFO : Aggregator started
2021-01-23 20:29:09,831 : INFO : Cryptostore started
2021-01-23 20:29:09,831 : INFO : Aggregator running on PID 4523
2021-01-23 20:29:09,843 : INFO : start: ['BITMEX'] stop: []
2021-01-23 20:29:09,844 : INFO : message: {"op": "start", "exchange": "BITMEX", "collector": {"channel_timeouts": {"l2_book": 30, "trades": 120, "ticker": 120, "funding": -1}, "retries": -1, "l2_book": {"symbols": ["XBTUSD"], "max_depth": 10, "book_delta": true, "book_interval": 100000}, "trades": ["XBTUSD"], "ticker": ["XBTUSD"], "funding": ["XBTUSD"]}, "config": {"cache": "redis", "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["arctic"], "storage_retries": 5, "storage_retry_wait": 30, "pass_through": {"type": "zmq", "host": "127.0.0.1", "port": 5678}, "parquet": {"del_file": true, "append_counter": 4, "file_format": ["exchange", "pair", "data_type", "timestamp"], "compression": {"codec": "BROTLI", "level": 6}, "path": null, "prefix_date": false, "S3": {"endpoint": null, "key_id": null, "secret": null, "bucket": null, "prefix": null}, "GCS": {"service_account": null, "bucket": null, "prefix": null}, "GD": {"service_account": null, "prefix": null, "folder_name_sep": "."}}, "arctic": "mongodb://192.168.137.21:27017", "storage_interval": 60}}
2021-01-23 20:29:09,844 : INFO : Starting {'op': 'start', 'exchange': 'BITMEX', 'collector': {'channel_timeouts': {'l2_book': 30, 'trades': 120, 'ticker': 120, 'funding': -1}, 'retries': -1, 'l2_book': {'symbols': ['XBTUSD'], 'max_depth': 10, 'book_delta': True, 'book_interval': 100000}, 'trades': ['XBTUSD'], 'ticker': ['XBTUSD'], 'funding': ['XBTUSD']}, 'config': {'cache': 'redis', 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['arctic'], 'storage_retries': 5, 'storage_retry_wait': 30, 'pass_through': {'type': 'zmq', 'host': '127.0.0.1', 'port': 5678}, 'parquet': {'del_file': True, 'append_counter': 4, 'file_format': ['exchange', 'pair', 'data_type', 'timestamp'], 'compression': {'codec': 'BROTLI', 'level': 6}, 'path': None, 'prefix_date': False, 'S3': {'endpoint': None, 'key_id': None, 'secret': None, 'bucket': None, 'prefix': None}, 'GCS': {'service_account': None, 'bucket': None, 'prefix': None}, 'GD': {'service_account': None, 'prefix': None, 'folder_name_sep': '.'}}, 'arctic': 'mongodb://192.168.137.21:27017', 'storage_interval': 60}}
2021-01-23 20:29:09,846 : INFO : Collector for BITMEX running on PID 4525
2021-01-23 20:29:09,887 : INFO : Flushing cache
/mnt/venv/cryptostore/lib/python3.7/site-packages/arctic/_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
/mnt/venv/cryptostore/lib/python3.7/site-packages/arctic/store/_pandas_ndarray_store.py:6: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import DataFrame, Series, Panel
2021-01-23 20:29:10,463 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 20:29:10,464 : INFO : No data for BITMEX-l2_book-XBTUSD
2021-01-23 20:29:10,464 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 20:29:10,464 : INFO : No data for BITMEX-trades-XBTUSD
2021-01-23 20:29:10,464 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 20:29:10,464 : INFO : No data for BITMEX-ticker-XBTUSD
2021-01-23 20:29:10,464 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 20:29:10,464 : INFO : No data for BITMEX-funding-XBTUSD
2021-01-23 20:30:09,904 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 20:30:09,908 : INFO : l2_book-BITMEX-XBTUSD: Read 1763 messages from Redis
WARNING:arctic.chunkstore.chunkstore:Library created, but couldn't enable sharding: no such command: 'enablesharding', full error: {'ok': 0.0, 'errmsg': "no such command: 'enablesharding'", 'code': 59, 'codeName': 'CommandNotFound'}. This is OK if you're not 'admin'
2021-01-23 20:30:10,261 : INFO : l2_book-BITMEX-XBTUSD: Removed 1763 entries through id 1611433809668-0
2021-01-23 20:30:10,261 : INFO : Write Complete BITMEX-l2_book-XBTUSD
2021-01-23 20:30:10,261 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 20:30:10,261 : INFO : trades-BITMEX-XBTUSD: Read 76 messages from Redis
2021-01-23 20:30:10,285 : INFO : trades-BITMEX-XBTUSD: Removed 76 entries through id 1611433809668-0
2021-01-23 20:30:10,285 : INFO : Write Complete BITMEX-trades-XBTUSD
2021-01-23 20:30:10,285 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 20:30:10,288 : INFO : ticker-BITMEX-XBTUSD: Read 752 messages from Redis
2021-01-23 20:30:10,318 : INFO : ticker-BITMEX-XBTUSD: Removed 752 entries through id 1611433810006-1
2021-01-23 20:30:10,318 : INFO : Write Complete BITMEX-ticker-XBTUSD
2021-01-23 20:30:10,318 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 20:30:10,318 : INFO : funding-BITMEX-XBTUSD: Read 1 messages from Redis
2021-01-23 20:30:10,340 : INFO : funding-BITMEX-XBTUSD: Removed 1 entries through id 1611433750539-0
2021-01-23 20:30:10,340 : INFO : Write Complete BITMEX-funding-XBTUSD
2021-01-23 20:31:09,915 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 20:31:09,919 : INFO : l2_book-BITMEX-XBTUSD: Read 2082 messages from Redis
2021-01-23 20:31:10,029 : INFO : l2_book-BITMEX-XBTUSD: Removed 2082 entries through id 1611433869877-0
2021-01-23 20:31:10,029 : INFO : Write Complete BITMEX-l2_book-XBTUSD
2021-01-23 20:31:10,029 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 20:31:10,029 : INFO : trades-BITMEX-XBTUSD: Read 71 messages from Redis
2021-01-23 20:31:10,063 : INFO : trades-BITMEX-XBTUSD: Removed 71 entries through id 1611433866867-0
2021-01-23 20:31:10,063 : INFO : Write Complete BITMEX-trades-XBTUSD
2021-01-23 20:31:10,064 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 20:31:10,067 : INFO : ticker-BITMEX-XBTUSD: Read 945 messages from Redis
2021-01-23 20:31:10,105 : INFO : ticker-BITMEX-XBTUSD: Removed 945 entries through id 1611433870007-4
2021-01-23 20:31:10,105 : INFO : Write Complete BITMEX-ticker-XBTUSD
2021-01-23 20:31:10,105 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 20:31:10,106 : INFO : No data for BITMEX-funding-XBTUSD
2021-01-23 20:32:09,929 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 20:32:09,933 : INFO : l2_book-BITMEX-XBTUSD: Read 2003 messages from Redis
2021-01-23 20:32:10,039 : INFO : l2_book-BITMEX-XBTUSD: Removed 2003 entries through id 1611433929798-0
2021-01-23 20:32:10,039 : INFO : Write Complete BITMEX-l2_book-XBTUSD
2021-01-23 20:32:10,039 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 20:32:10,039 : INFO : trades-BITMEX-XBTUSD: Read 51 messages from Redis
2021-01-23 20:32:10,071 : INFO : trades-BITMEX-XBTUSD: Removed 51 entries through id 1611433907218-0
2021-01-23 20:32:10,072 : INFO : Write Complete BITMEX-trades-XBTUSD
2021-01-23 20:32:10,072 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 20:32:10,074 : INFO : ticker-BITMEX-XBTUSD: Read 731 messages from Redis
2021-01-23 20:32:10,122 : INFO : ticker-BITMEX-XBTUSD: Removed 731 entries through id 1611433928003-3
2021-01-23 20:32:10,122 : INFO : Write Complete BITMEX-ticker-XBTUSD
2021-01-23 20:32:10,122 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 20:32:10,123 : INFO : No data for BITMEX-funding-XBTUSD
2021-01-23 20:33:09,941 : INFO : Reading BITMEX-l2_book-XBTUSD
2021-01-23 20:33:09,944 : INFO : l2_book-BITMEX-XBTUSD: Read 1904 messages from Redis
2021-01-23 20:33:10,059 : INFO : l2_book-BITMEX-XBTUSD: Removed 1904 entries through id 1611433989930-0
2021-01-23 20:33:10,059 : INFO : Write Complete BITMEX-l2_book-XBTUSD
2021-01-23 20:33:10,059 : INFO : Reading BITMEX-trades-XBTUSD
2021-01-23 20:33:10,060 : INFO : trades-BITMEX-XBTUSD: Read 76 messages from Redis
2021-01-23 20:33:10,093 : INFO : trades-BITMEX-XBTUSD: Removed 76 entries through id 1611433988994-1
2021-01-23 20:33:10,094 : INFO : Write Complete BITMEX-trades-XBTUSD
2021-01-23 20:33:10,094 : INFO : Reading BITMEX-ticker-XBTUSD
2021-01-23 20:33:10,096 : INFO : ticker-BITMEX-XBTUSD: Read 663 messages from Redis
2021-01-23 20:33:10,129 : INFO : ticker-BITMEX-XBTUSD: Removed 663 entries through id 1611433990053-1
2021-01-23 20:33:10,129 : INFO : Write Complete BITMEX-ticker-XBTUSD
2021-01-23 20:33:10,129 : INFO : Reading BITMEX-funding-XBTUSD
2021-01-23 20:33:10,130 : INFO : No data for BITMEX-funding-XBTUSD
```

**Comment by JamesKBowler** [comment]
Well its been running all night with zero issues.

Time to read the source code : )

Thank you for producing a fine piece of work and the level support is great.

**Comment by bmoscon** [comment]
@JamesKBowler glad its working :)

**Comment by grigored** [comment]
I'm seeing the error `ImportError: cannot import name 'Panel' from 'pandas' (/mnt/venv/cryptostore/lib/python3.8/site-packages/pandas/__init__.py)` when running in docker as well. I solved this by adding `RUN pip install --no-cache-dir pandas==1.1.5` in Dockerfile before all the other pip installs

**Comment by bmoscon** [comment]
@grigored thats an issue with arctic, not cryptostore.
