### ISSUE TITLE
Failed to subscribe to open interest on binance futures

### ISSUE THREAD

**Issue by ph4z** [bmoscon/cryptostore#153]
See the error below:

````
2021-01-30 16:57:22,120 : INFO : Reading BINANCE_FUTURES-open_interest-BTC-USDT
2021-01-30 16:57:22,120 : INFO : No data for BINANCE_FUTURES-open_interest-BTC-USDT
Process Collector-1:1:
Traceback (most recent call last):
  File "/home/ph4z/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ph4z/miniconda3/lib/python3.8/site-packages/cryptostore/collector.py", line 122, in run
    fh.run()
  File "/home/ph4z/miniconda3/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 232, in run
    for conn, sub, handler in feed.connect():
  File "/home/ph4z/miniconda3/lib/python3.8/site-packages/cryptofeed/feed.py", line 132, in connect
    for _, addr in self.address.items():
AttributeError: 'NoneType' object has no attribute 'items'
````

This is weird because when I directly use cryptofeed to get the open interest it works as expected.
Using other exchanges like okex is ok.
It seems to fail only for binance open interest and just before the connection is initiated.

**Comment by bmoscon** [comment]
This should be fixed now @ph4z - but you'll need to use the latest version of cryptofeed from github
