### ISSUE TITLE
Cryptofeed error on config

### ISSUE THREAD

**Issue by emiliobasualdo** [bmoscon/cryptostore#160]
**Describe the bug**
`TypeError: type object got multiple values for keyword argument 'config'`
python 3.8
Redis server v=6.0.9
mongodb 4.4.4
**To Reproduce**
```
pip install git+https://github.com/manahl/arctic.git
pip install cryptostore[redis]
cryptostore
```
* Provide config (at least as much as is relevant)

```
# Cryptostore sample config file

cache: redis
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    COINBASE:
        retries: -1
        trades: [BTC-USD]

storage: [arctic]
storage_retries: 5
storage_retry_wait: 30
storage_interval: 60

arctic: mongodb://127.0.0.1

```
* redis or kafka?
 redis
* What behavior did you see?
Error msg and now data saved to mongo.
* Provide any tracebacks if applicable
```
[ec2-user@ip-172-31-38-156 ~]$ cryptostore
2021-02-21 23:08:15,640 : INFO : Starting cryptostore
2021-02-21 23:08:15,640 : INFO : Cryptostore running on PID 30626
2021-02-21 23:08:15,643 : INFO : Spawner started
2021-02-21 23:08:15,644 : INFO : Spawner running on PID 30632
2021-02-21 23:08:15,645 : INFO : Aggregator started
2021-02-21 23:08:15,646 : INFO : Aggregator running on PID 30633
2021-02-21 23:08:15,647 : INFO : Cryptostore started
2021-02-21 23:08:15,650 : INFO : start: ['COINBASE'] stop: []
2021-02-21 23:08:15,651 : INFO : message: {"op": "start", "exchange": "COINBASE", "collector": {"retries": -1, "trades": ["BTC-USD"]}, "config": {"cache": "redis", "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["arctic"], "storage_retries": 5, "storage_retry_wait": 30, "storage_interval": 5, "arctic": "mongodb://127.0.0.1"}}
2021-02-21 23:08:15,652 : INFO : Starting {'op': 'start', 'exchange': 'COINBASE', 'collector': {'retries': -1, 'trades': ['BTC-USD']}, 'config': {'cache': 'redis', 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['arctic'], 'storage_retries': 5, 'storage_retry_wait': 30, 'storage_interval': 5, 'arctic': 'mongodb://127.0.0.1'}}
2021-02-21 23:08:15,656 : INFO : Collector for COINBASE running on PID 30635
2021-02-21 23:08:15,659 : INFO : Flushing cache
Process Collector-1:1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/cryptostore/collector.py", line 122, in run
    fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, snapshot_interval=snap_interval, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 175, in add_feed
    self.feeds.append((_EXCHANGES[feed](config=self.config, **kwargs), timeout))
TypeError: type object got multiple values for keyword argument 'config'
2021-02-21 23:08:15,761 : INFO : Reading COINBASE-trades-BTC-USD
2021-02-21 23:08:15,761 : INFO : No data for COINBASE-trades-BTC-USD
```

**Operating System:**
AWS linux 

**Cryptofeed Version**
cryptofeed        1.7.0
cryptostore       0.3.1

**Comment by bmoscon** [comment]
version mismatch - newer versions of cryptostore and cryptofeed renamed params, please update to cryptostore

**Comment by emiliobasualdo** [comment]
Understood, thanks!
