### ISSUE TITLE
Cryptostore does not work with latest version of cryptofeed (v.1.9.3)

### ISSUE THREAD

**Issue by jeffneuen** [bmoscon/cryptostore#192]
When attempting to run cryptostore, it does not run due to changes in cryptofeed. On attempting to run cryptostore, the following error is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/cryptostore", line 11, in <module>
    load_entry_point('cryptostore', 'console_scripts', 'cryptostore')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/cryptostore/__init__.py", line 1, in <module>
    from cryptostore.cryptostore import Cryptostore
  File "/cryptostore/cryptostore.py", line 13, in <module>
    from cryptostore.spawn import Spawn
  File "/cryptostore/spawn.py", line 12, in <module>
    from cryptostore.collector import Collector
  File "/cryptostore/collector.py", line 13, in <module>
    from cryptofeed.defines import TRADES, L2_BOOK, L3_BOOK, MARKET_INFO, BOOK_DELTA, TICKER, FUNDING, OPEN_INTEREST, LIQUIDATIONS, CANDLES
ImportError: cannot import name 'MARKET_INFO' from 'cryptofeed.defines' (/usr/local/lib/python3.7/site-packages/cryptofeed/defines.py)
```

I poked around in cryptofeed a little bit, and saw that "MARKET _INFO" was recently removed from cryptofeed/defines.py in this commit: https://github.com/bmoscon/cryptofeed/commit/b0745d9365638b4fe9472abc7dacf886027d983e so I'm guessing it was part of the symbol standardization. 

Pinning cryptofeed to 1.9.2 does fix this issue (the MKT_INFO issue), although I am still verifying that no other issues pop up with my config.

**Comment by robertsmd** [comment]
confirmed issue with the docker-compose setup. easily solved by changing line in Dockerfile:

`RUN pip install --no-cache-dir git+https://github.com/bmoscon/cryptofeed.git`
with
`RUN pip install --no-cache-dir cryptofeed==1.9.2`

**Comment by bmoscon** [comment]
market info was removed, the code was updated in cryptostore
