### ISSUE TITLE
Redis invalid input error thrown when using fundiing or open interest on FTX

### ISSUE THREAD

**Issue by jeffneuen** [bmoscon/cryptostore#195]
When attempting to capture funding and open interest on FTX perps, redis throws an error:

```
future: <Task finished coro=<RedisStreamCallback.writer() done, defined at /usr/local/lib/python3.7/site-packages/cryptofeed/backends/redis.py:90> exception=DataError("Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 104, in writer
    await self.redis.xadd(f"{self.key}-{update['exchange']}-{update['symbol']}", update)
  File "/usr/local/lib/python3.7/site-packages/aioredis/client.py", line 1036, in execute_command
    await conn.send_command(*args)
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 835, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 879, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 123, in encode
    f"Invalid input of type: {typename!r}. "
aioredis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```
The following sample config should reproduce the error. With funding and open_interest commented out, it works fine. Uncommenting either of them throws the error.

```
cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

exchanges:    
    FTX:
      retries: -1
      l2_book:
        symbols: [LTC-USD-PERP, LTC-BTC, BTC-USD-PERP, ETH-BTC, ETH-USD-PERP]
        book_delta: true
        book_interval: 100000
      
      #funding: [LTC-USD-PERP, BTC-USD-PERP, ETH-USD-PERP]
      #open_interest: [LTC-USD-PERP, BTC-USD-PERP, ETH-USD-PERP]
      liquidations: [LTC-USD-PERP, BTC-USD-PERP, ETH-USD-PERP]
      ticker: [LTC-USD-PERP, BTC-USD-PERP, ETH-USD-PERP]
      trades: [LTC-USD-PERP, BTC-USD-PERP, ETH-USD-PERP]

storage: [parquet]

parquet:
  file_format: [exchange, symbol, data_type, timestamp]  
  del_file: true
  compression:
    codec: 'BROTLI'
  path: /tmp
  prefix_date: false
  append_counter: 60

storage_interval: 60
storage_retries: 10
storage_retry_wait: 30
```

Latest version of cryptofeed, installing from git via Dockerfile.

**Comment by bmoscon** [comment]
should be fixed now, but you need to use the latest version of cryptofeed in github
