### ISSUE TITLE
ValueError: could not convert string to float: 'None'

### ISSUE THREAD

**Issue by JamesKBowler** [bmoscon/cryptostore#198]
**Describe the bug**

After upgrading code to the latest versions for both Cryptofeed and CryptoStore to fix [this](https://github.com/bmoscon/cryptofeed/issues/709) issue, I now have the following issue with Influx.

Please help, thank you

```
2021-11-08 22:08:26,803 : ERROR : Influx: Failed to write data to http://192.168.137.201:8086/api/v2/write?org=crypto&bucket=crypto_data&precision=ns - 400:Bad Request
2021-11-08 22:08:56,811 : INFO : l3_book-BITFINEX-BTC-USD: Removed 230 entries through id 1636409306776-24
2021-11-08 22:08:56,811 : INFO : Write Complete BITFINEX-l3_book-BTC-USD
2021-11-08 22:08:56,811 : INFO : Reading BITFINEX-trades-BTC-USD
2021-11-08 22:08:56,817 : INFO : trades-BITFINEX-BTC-USD: Read 32 messages from Redis
2021-11-08 22:08:56,874 : INFO : trades-BITFINEX-BTC-USD: Removed 32 entries through id 1636409314073-0
2021-11-08 22:08:56,874 : INFO : Write Complete BITFINEX-trades-BTC-USD
2021-11-08 22:08:56,874 : INFO : Reading BITFINEX-ticker-BTC-USD
2021-11-08 22:08:56,875 : INFO : ticker-BITFINEX-BTC-USD: Read 4 messages from Redis
2021-11-08 22:08:56,875 : ERROR : Aggregator running on PID 22 died due to exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 92, in loop
    data = cache.read(exchange, dtype, pair, start=start, end=end)
  File "/usr/local/lib/python3.7/site-packages/cryptostore/aggregator/redis.py", line 71, in read
    update[k] = float(update[k])
ValueError: could not convert string to float: 'None'
Task exception was never retrieved
future: <Task finished coro=<Aggregator.loop() done, defined at /usr/local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py:43> exception=ValueError("could not convert string to float: 'None'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 92, in loop
    data = cache.read(exchange, dtype, pair, start=start, end=end)
  File "/usr/local/lib/python3.7/site-packages/cryptostore/aggregator/redis.py", line 71, in read
    update[k] = float(update[k])
ValueError: could not convert string to float: 'None'

```

**Operating System:**
 - Ubuntu 20.04

**Cryptofeed Version**
v2.0.3

**Comment by bmoscon** [comment]
fixed today in crytpofeed
