### ISSUE TITLE
Error reading config.yaml

### ISSUE THREAD

**Issue by Leo-ich** [bmoscon/cryptostore#205]
**Describe the bug**
If in config.yaml
```
exchanges:
    BITFINEX:
        l2_book:
            symbols: [ BTC-USD ]
```
error:
```
Process Collector-1:1:
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python38\lib\site-packages\cryptostore\collector.py", line 136, in run
    fh.add_feed(self.exchange, subscription={callback_type: self.exchange_config[callback_type]}, callbacks=cb, **feed_k
wargs)
  File "C:\Python38\lib\site-packages\cryptofeed\feedhandler.py", line 93, in add_feed
    self.feeds.append((EXCHANGE_MAP[feed](config=self.config, **kwargs)))
  File "C:\Python38\lib\site-packages\cryptofeed\exchanges\bitfinex.py", line 110, in __init__
    super().__init__(symbols=symbols, channels=channels, subscription=subscription, **kwargs)
  File "C:\Python38\lib\site-packages\cryptofeed\feed.py", line 95, in __init__
    raise ValueError("Use subscription, or channels and symbols, not both")
ValueError: Use subscription, or channels and symbols, not both
```
If in config.yaml
```
exchanges:
    KRAKEN:
        l2_book:
            symbols: [ BTC-USD ]
```
no errors, it works.

Feedhandler gets an unnecessary list symbols, if exchanges is Bitfinex.

**Operating System:**
 Windows

**Cryptofeed Version**
cryptofeed 2.1.1

**Cryptostore Version**
cryptostore 0.4.0

**Comment by basgir** [comment]
I do have the same problem with Hitbtc when I try to fetch the l2_book:
```
exchanges:
    HITBTC:
        l2_book:
            symbols: [ BTC-USDT ]
```

**Comment by bmoscon** [comment]
old version is deprecated, closing
