### ISSUE TITLE
[Kraken Futures] ValueError: Use subscription, or channels and symbols, not both

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptostore#206]
Config:

https://pastebin.com/iE9Q07js

I'm trying to subscribe to all supported channels for one symbol (`L2_BOOK, TICKER, TRADES, OPEN_INTEREST, FUNDING`), but getting:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/anov/IdeaProjects/cryptostore/cryptostore/collector.py", line 136, in run
    fh.add_feed(self.exchange, subscription={callback_type: self.exchange_config[callback_type]}, callbacks=cb, **feed_kwargs)
  File "/Users/anov/IdeaProjects/cryptofeed/cryptofeed/feedhandler.py", line 95, in add_feed
    self.feeds.append((EXCHANGE_MAP[feed](config=self.config, **kwargs)))
  File "/Users/anov/IdeaProjects/cryptofeed/cryptofeed/feed.py", line 114, in __init__
    raise ValueError("Use subscription, or channels and symbols, not both")
ValueError: Use subscription, or channels and symbols, not both
```

This is thrown on `FUNDING` channel.

Looking through code, I'm not completely sure how this works since for `KrakenFutures` object `FUNDING` and `OPEN_INTEREST` ws channels use the same endpoint (is it ok?) Another part that confuses me is `async def _funding` triggers callbacks for both `FUNDING` and `OPEN_INTEREST`. I feel like I should somehow change the way I subscribe, could you elaborate a bit please?

**Comment by bmoscon** [comment]
old version is deprecated, closing
