### ISSUE TITLE
Some exchanges are not supported !

### ISSUE THREAD

**Issue by KamranBiglari** [bmoscon/cryptostore#216]
**Describe the bug**
I tried to use `CryptoDotCom` , `MIXINS` and `BITDOTCOM` but it's not supported !

```
docker run -e EXCHANGE=BITDOTCOM -e CHANNELS=trades,ticker -e SYMBOLS=BTC-USD,BTC-USDT,BTC-USDC,BTC-BUSD,ETH-USD,ETH-USDT,ETH-USDC,ETH-BUSD,USDT-USD,USDC-USD,BUSD-USD -e BACKEND=REDIS -e HOST=xxxxx -e CONFIG=./config.yaml ncfx-cryptofeed:latest
Traceback (most recent call last):
  File "/cryptostore.py", line 161, in <module>
    main()
  File "/cryptostore.py", line 155, in main
    cfg = load_config()
  File "/cryptostore.py", line 150, in load_config
    return EXCHANGE_MAP[exchange](candle_intterval=candle_interval, symbols=symbols, channels=channels, config=config, callbacks=cbs)
KeyError: 'BITDOTCOM'
```

**Comment by iamkucuk** [comment]
This is not a bug. This may fall into feature request.

Cryptostore is a wrapper (a thin one) which heavily relies on cryptofeed. You will find yourself looking into cryptofeed's docs more than cryptostore's only doc page.

**Comment by bmoscon** [comment]
its because cryptostore needs to be updated to pull in the later version of cryptofeed
