### ISSUE TITLE
Error with GEMINI using only one pair.

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#22]
```
2019-07-25 14:56:51,525 : INFO : message: {"op": "start", "exchange": "GEMINI", "collector": {"l2_book": ["BTC-USD"], "trades": ["BTC-USD"]}, "config": {"cache": "redis", "kafka": {"ip": "127.0.0.1", "port": 9092, "start_flush": true}, "redis": {"ip": "127.0.0.1", "port": 6379, "del_after_read": true, "start_flush": true}, "book_depth": null, "book_delta": true, "book_delta_window": 10000, "storage": ["influx", "parquet"], "pass_through": {"type": "zmq", "host": "127.0.0.1", "port": 5678}, "elastic": {"host": "http://localhost:9200", "user": null, "token": null}, "influx": {"host": "http://127.0.0.1:8086", "db": "market_data", "create": true}, "parquet": null, "arctic": "mongodb://127.0.0.1", "storage_interval": 3600, "plugins": {"backfill": {"module": ["cryptostore.plugin.backfill", "Backfill"], "config": "config_xiandong.yaml"}}, "backfill": null}}
2019-07-25 14:56:51,525 : INFO : Starting {'op': 'start', 'exchange': 'GEMINI', 'collector': {'l2_book': ['BTC-USD'], 'trades': ['BTC-USD']}, 'config': {'cache': 'redis', 'kafka': {'ip': '127.0.0.1', 'port': 9092, 'start_flush': True}, 'redis': {'ip': '127.0.0.1', 'port': 6379, 'del_after_read': True, 'start_flush': True}, 'book_depth': None, 'book_delta': True, 'book_delta_window': 10000, 'storage': ['influx', 'parquet'], 'pass_through': {'type': 'zmq', 'host': '127.0.0.1', 'port': 5678}, 'elastic': {'host': 'http://localhost:9200', 'user': None, 'token': None}, 'influx': {'host': 'http://127.0.0.1:8086', 'db': 'market_data', 'create': True}, 'parquet': None, 'arctic': 'mongodb://127.0.0.1', 'storage_interval': 3600, 'plugins': {'backfill': {'module': ['cryptostore.plugin.backfill', 'Backfill'], 'config': 'config_xiandong.yaml'}}, 'backfill': None}}

2019-07-25 14:56:51,530 : INFO : Collector for GEMINI running on PID 12121

Traceback (most recent call last):
 File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
   self.run()
 File "/home/xiandong/.local/lib/python3.6/site-packages/cryptostore/collector.py", line 64, in run
   fh.add_feed(self.exchange, book_interval=window, config=self.exchange_config, callbacks=cb)
 File "/home/xiandong/.local/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 77, in add_feed
   self.feeds.append(_EXCHANGES[feed](**kwargs))
 File "/home/xiandong/.local/lib/python3.6/site-packages/cryptofeed/gemini/gemini.py", line 26, in __init__
   if len(pairs) != 1:
TypeError: object of type 'NoneType' has no len()
```

**cryptostore version 0.0.8
cryptofeed version 0.25.0**

**Comment by xiandong79** [comment]
Wow, why not publish the latest version to PyPI? @bmoscon

**Comment by cheekybastard** [comment]
@xiandong79 Pip can install straight from any public github repo and you get the latest commits on the branch you select.

pip install https://github.com/bmoscon/cryptostore/zipball/master https://github.com/bmoscon/cryptofeed/zipball/master

**Comment by bmoscon** [comment]
@xiandong79 gemini will not work with cryptostore. I'll put in something to not let you select it until Ive changed cryptofeed to support it like the other exchanges

**Comment by xiandong79** [comment]
> @xiandong79 gemini will not work with cryptostore. I'll put in something to not let you select it until Ive changed cryptofeed to support it like the other exchanges

Yes. it would be great that users can know it when reading the README.md
