### ISSUE TITLE
POLONIEX: missing sequence number. Received 2, expected 406241931

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#23]
```
2019-07-25 14:56:51,528 : INFO : message: {"op": "start", "exchange": "POLONIEX", "collector": {"l2_book": ["BTC-USDT"], "trades": ["BTC-USDT"]}, "config": {"cache": "redis", "kafka": {"ip": "127.0.0.1", "port": 9092, "start_flush": true}, "redis": {"ip": "127.0.0.1", "port": 6379, "del_after_read": true, "start_flush": true}, "book_depth": null, "book_delta": true, "book_delta_window": 10000, "storage": ["influx", "parquet"], "pass_through": {"type": "zmq", "host": "127.0.0.1", "port": 5678}, "elastic": {"host": "http://localhost:9200", "user": null, "token": null}, "influx": {"host": "http://127.0.0.1:8086", "db": "market_data", "create": true}, "parquet": null, "arctic": "mongodb://127.0.0.1", "storage_interval": 3600, "plugins": {"backfill": {"module": ["cryptostore.plugin.backfill", "Backfill"], "config": "config_xiandong.yaml"}}, "backfill": null}}
2019-07-25 14:56:51,529 : INFO : Starting {'op': 'start', 'exchange': 'POLONIEX', 'collector': {'l2_book': ['BTC-USDT'], 'trades': ['BTC-USDT']}, 'config': {'cache': 'redis', 'kafka': {'ip': '127.0.0.1', 'port': 9092, 'start_flush': True}, 'redis': {'ip': '127.0.0.1', 'port': 6379, 'del_after_read': True, 'start_flush': True}, 'book_depth': None, 'book_delta': True, 'book_delta_window': 10000, 'storage': ['influx', 'parquet'], 'pass_through': {'type': 'zmq', 'host': '127.0.0.1', 'port': 5678}, 'elastic': {'host': 'http://localhost:9200', 'user': None, 'token': None}, 'influx': {'host': 'http://127.0.0.1:8086', 'db': 'market_data', 'create': True}, 'parquet': None, 'arctic': 'mongodb://127.0.0.1', 'storage_interval': 3600, 'plugins': {'backfill': {'module': ['cryptostore.plugin.backfill', 'Backfill'], 'config': 'config_xiandong.yaml'}}, 'backfill': None}}

2019-07-25 14:56:51,533 : INFO : Collector for POLONIEX running on PID 121222019-07-25 14:56:54,208 : WARNING : POLONIEX: missing sequence number. Received 2, expected 406241931
2019-07-25 14:56:54,208 : ERROR : POLONIEX: error handling message [121,2]
2019-07-25 14:56:54,481 : ERROR : POLONIEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/xiandong/.local/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 172, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/xiandong/.local/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 190, in _handler
    await handler(message)
  File "/home/xiandong/.local/lib/python3.6/site-packages/cryptofeed/poloniex/poloniex.py", line 178, in message_handler
    raise MissingSequenceNumber
cryptofeed.exceptions.MissingSequenceNumber
```

**cryptostore version 0.0.8
cryptofeed version 0.25.0**

**Comment by bmoscon** [comment]
I'll see if I can reproduce this

**Comment by xiandong79** [comment]
this is not resolved by the lastest version code.

**Comment by bmoscon** [comment]
Book deltas arent supported by poloniex, but they should be. Going to fix this on the cryptofeed side

**Comment by bmoscon** [comment]
fixed on cryptofeed. its in master, will be in pypi sometime in the near future
