### ISSUE TITLE
Huobi - TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#25]
config.yaml
```
# Trading pairs for all exchanges (except BitMEX) follow the currency-quote format
exchanges:
    HUOBI:
        l2_book: [BTC-USDT, ETH-USDT]
        trades: [BTC-USDT, ETH-USDT]
# Number of levels per side to store from book updates.
# Remove this option to store all available data.
# Cannot enable book_depth with book_deltas
book_depth: null

# Store book deltas as opposed to complete books on every update
# Cannot enable book deltas with book_depth (delta will be ignored if depth enabled).
# Not all exchanges support deltas
book_delta: True
# Number of deltas between full book updates
book_delta_window: 10000
```

Error info:
```
2019-07-30 16:39:30,525 : ERROR : HUOBI: error handling message b'{"ch":"market.btcusdt.depth.step0","ts":1564475969212,"tick":{"bids":[[9484.48,2.0],[9484.13,0.0509],[9484.01,0.285271],[9483.86,0.061],[9483.05,3.55E-4],[9481.85,0.003],[9481.8,0.5],[9481.58,0.2],[9481.15,0.23],[9481.0,0.4],[9480.62,0.2999],[9480.61,0.5294],[9480.6,1.9618],[9480.01,1.413979],[9480.0,3.98389],[9479.59,0.04],[9479.57,4.0E-4],[9478.51,1.0033],[9478.42,0.005],[9478.23,0.101501],[9478.21,0.0294],[9477.83,2.846893],[9477.55,2.0E-4],[9477.47,0.316291],[9477.21,1.897467],[9476.78,0.054924],[9476.51,1.264742],[9476.34,5.0E-4],[9476.29,1.4],[9476.27,3.55E-4],[9476.19,1.66E-4],[9476.0,0.109847],[9475.48,0.304738],[9475.42,0.0015],[9475.0,0.593707],[9474.56,3.6E-4],[9474.49,0.3679],[9474.34,0.240667],[9474.21,6.193481],[9473.56,2.530572],[9473.44,0.16474],[9473.41,1.265029],[9473.31,0.611827],[9473.1,0.0013],[9472.98,0.494219],[9472.8,0.422261],[9472.71,1.265029],[9472.4,0.316247],[9471.66,0.003],[9471.62,0.2862],[9471.29,1.5],[9471.26,0.105418],[9470.85,0.054949],[9470.64,0.115],[9470.38,0.007416],[9470.08,0.0101],[9470.0,0.409524],[9469.49,3.55E-4],[9469.42,0.32],[9469.38,0.00744],[9469.3,0.004],[9469.14,0.0526],[9468.88,0.032107],[9468.82,0.055798],[9468.57,0.9918],[9468.44,0.105429],[9468.36,0.316285],[9468.14,2.0],[9468.0,0.030472],[9467.14,0.105428],[9466.97,0.0013],[9466.9,0.25],[9466.5,0.25],[9465.86,0.6],[9465.73,0.63],[9465.43,4.0E-4],[9465.0,1.0],[9464.93,0.0031],[9464.32,0.316285],[9464.31,0.105428],[9464.0,1.0],[9463.72,0.0094],[9463.7,0.0152],[9463.62,0.003],[9463.5,4.0E-4],[9463.16,0.0056],[9463.12,0.38],[9462.88,2.0E-4],[9462.71,3.55E-4],[9462.65,0.25],[9462.27,0.001],[9462.1,2.0E-4],[9461.67,2.0E-4],[9461.55,0.0014],[9461.5,0.316289],[9461.26,2.0E-4],[9461.0,0.008878],[9460.9,0.25],[9460.26,2.0E-4],[9460.1,0.25],[9460.04,0.0024],[9460.0,1.140008],[9459.98,0.316285],[9459.95,0.0574],[9459.51,0.0022],[9459.18,0.001429],[9458.9,0.25],[9458.59,2.0E-4],[9458.56,0.0522],[9458.33,0.001289],[9458.1,0.005691],[9458.03,0.002],[9457.64,4.0E-4],[9457.62,0.012156],[9457.55,0.0068],[9457.49,3.01E-4],[9457.43,5.0E-4],[9457.14,0.02094],[9457.0,1.001],[9456.61,0.002],[9456.51,0.0015],[9456.0,0.015173],[9455.97,0.001679],[9455.93,3.55E-4],[9455.66,5.0E-4],[9455.0,0.046739],[9454.27,0.5745],[9454.0,2.245946],[9453.86,3.96E-4],[9453.4,0.25],[9453.06,0.04],[9453.0,1.0],[9452.94,0.533029],[9452.63,0.01202],[9452.0,0.567498],[9451.7,2.0E-4],[9451.62,0.009],[9451.61,0.022],[9451.55,9.0E-4],[9451.3,0.25],[9450.85,0.185157],[9450.64,0.0012],[9450.57,3.0E-4],[9450.01,4.0E-4],[9450.0,6.100307],[9449.83,0.001238],[9449.42,1.36E-4],[9449.3,0.00806],[9449.25,0.003],[9449.15,3.55E-4]],"asks":[[9485.7,0.392797],[9485.73,0.0056],[9485.74,0.641352],[9485.76,0.32835],[9485.79,0.613898],[9485.83,0.003899],[9485.99,0.0154],[9486.03,0.1198],[9486.04,0.1266],[9486.05,2.0],[9486.06,0.090047],[9486.38,0.3],[9486.47,1.057726],[9486.81,0.2],[9487.34,0.0515],[9487.38,0.011],[9487.42,0.01],[9488.06,0.475135],[9488.4,0.210647],[9488.44,2.5258],[9488.52,0.0515],[9488.74,0.012],[9488.79,1.5517],[9488.8,0.1369],[9488.81,9.94],[9489.06,0.350652],[9489.14,0.09742],[9489.2,2.0],[9489.22,0.602248],[9489.41,0.1],[9489.47,0.0711],[9489.52,0.0497],[9489.73,0.5292],[9490.0,0.300446],[9490.22,0.316291],[9490.29,1.5514],[9490.31,0.003],[9490.68,0.5217],[9491.39,0.1475],[9491.68,0.312715],[9491.98,0.491],[9492.17,0.2],[9492.19,0.632643],[9493.15,0.842713],[9493.26,0.948965],[9493.5,0.316274],[9493.74,0.0174],[9493.75,0.23],[9494.25,0.097262],[9494.4,0.03],[9494.47,1.265286],[9494.6,0.4093],[9494.67,0.054924],[9494.7,0.948737],[9494.72,0.109827],[9494.99,0.16474],[9495.27,0.003],[9495.46,0.494232],[9496.2,1.12],[9496.61,3.55E-4],[9497.21,0.054949],[9497.26,0.006025],[9497.55,0.524147],[9498.09,2.530178],[9498.3,0.7745],[9498.59,1.5],[9498.73,0.213857],[9498.74,2.530572],[9499.85,0.00274],[9500.04,0.059],[9500.61,0.134886],[9500.62,0.185185],[9500.9,0.421713],[9502.6,1.4],[9502.94,0.5064],[9503.0,1.0],[9503.05,0.210857],[9503.38,3.55E-4],[9503.48,0.003],[9503.62,0.210858],[9504.2,0.337157],[9504.23,0.210858],[9504.47,0.0109],[9504.48,0.025302],[9504.99,0.912369],[9505.0,2.518314],[9505.4,0.421708],[9505.88,0.0102],[9506.0,0.705],[9506.02,1.46],[9506.12,0.007578],[9506.33,0.421719],[9506.84,0.421714],[9507.3,0.421708],[9507.69,0.9918],[9507.9,0.045849],[9508.0,10.04386],[9508.66,2.4119],[9509.3,0.25],[9510.0,0.287318],[9510.09,0.3],[9510.16,3.55E-4],[9510.2,1.88E-4],[9510.38,0.159691],[9511.23,0.025303],[9511.6,0.0108],[9511.82,2.0],[9512.0,0.001033],[9512.24,1.38E-4],[9513.0,0.05],[9513.36,0.0015],[9513.38,0.015807],[9514.23,0.8],[9514.28,0.014],[9514.35,0.03],[9514.48,1.009452],[9515.0,0.976601],[9515.09,0.5],[9515.5,0.63],[9516.19,2.0],[9516.2,0.25],[9516.83,0.044619],[9516.88,0.0024],[9516.9,0.25],[9516.94,3.55E-4],[9518.0,0.316154],[9518.2,0.9988],[9518.36,0.007578],[9518.79,0.0526],[9519.49,0.76],[9519.51,2.523538],[9520.0,15.384355],[9520.06,0.17175],[9520.95,0.091088],[9521.0,0.416284],[9521.65,0.362646],[9521.82,0.381892],[9522.68,0.422073],[9523.0,0.056393],[9523.12,0.468637],[9523.17,0.015783],[9523.34,0.210831],[9523.65,0.052817],[9523.72,3.55E-4],[9523.8,0.25],[9523.98,0.002526],[9524.4,0.25],[9524.48,1.38E-4],[9525.0,5.23824],[9525.81,3.0E-4]],"version":101926915408,"ts":1564475969030}}'
2019-07-30 16:39:30,610 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/huobi/huobi.py", line 84, in message_handler
    await self._book(msg)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/huobi/huobi.py", line 47, in _book
    await self.book_callback(pair, L2_BOOK, False, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 61, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 72, in callback
    await cb(**kwargs)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 165, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```

**cryptofeed             1.0.0      
cryptostore            0.1.0**  
Latest code build from source code in github.

**Comment by bmoscon** [comment]
Huobi doesnt support book deltas, so you have to disable them by setting `book_delta: False`

I'm working on adding support for per exchange configs

**Comment by bmoscon** [comment]
this has been fixed on master
