### ISSUE TITLE
Poloniex backfill timestamp issue

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptostore#26]
Seems like the timestamp needs to be converted to second since the epoch when backfilling with Poloniex using Arctic:

```python
2019-07-31 12:43:51,379 : ERROR : Backfill failed for POLONIEX - BTC-USDT
Traceback (most recent call last):
  File "pandas/_libs/tslib.pyx", line 395, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: could not convert string to float: '2019-07-31 00:00:14'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/plugin/backfill.py", line 76, in _worker
    storage.write(exchange, 'trades', pair, end.timestamp())
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/data/storage.py", line 33, in write
    s.write(exchange, data_type, pair, timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/data/arctic.py", line 31, in write
    df['date'] = pd.to_datetime(df['timestamp'], unit='s')
  File "/home/nate/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 592, in to_datetime
    values = convert_listlike(arg._values, True, format)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 203, in _convert_listlike_datetimes
    errors=errors)
  File "pandas/_libs/tslib.pyx", line 398, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: non convertible value 2019-07-31 00:00:14 with the unit 's'
```

**Comment by nateGeorge** [comment]
It looks like the `unit=s` argument needs to be removed for Poloniex -- it'll work with `pd.to_datetime(df['timestamp'])`.  Not sure how you want to go about doing it though.  A try-except block?

**Comment by bmoscon** [comment]
I'll take a look, the date may not be being normalized correctly on the cryptofeed side

**Comment by bmoscon** [comment]
fixed in cryptofeed
