### ISSUE TITLE
Kraken backfill issue

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptostore#27]
This was working before with the pip-installed cryptofeed and cryptostore, but now using the latest github versions it doesn't seem to be working.  Backfill trades data for BTC-USD and ETH-USD results in the following error (using Arctic):

```python
2019-07-31 17:04:10,038 : INFO : Backfill - Starting for KRAKEN - BTC-USD for range 2009-01-01 00:00:00 - 2019-07-31 23:03:31.112868024
2019-07-31 17:04:10,038 : INFO : Backfill - Reading 2019-07-31 00:00:00 to 2019-07-31 23:03:31.112868024 for KRAKEN - BTC-USD
WARNING:root:Column 'price' type is mixed
2019-07-31 17:04:10,799 : ERROR : Backfill failed for KRAKEN - BTC-USD
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 83, in _convert_types
    a = np.array([s.encode('ascii') for s in a])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 83, in <listcomp>
    a = np.array([s.encode('ascii') for s in a])
AttributeError: 'float' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore-0.1.0-py3.6.egg/cryptostore/plugin/backfill.py", line 76, in _worker
    storage.write(exchange, 'trades', pair, end.timestamp())
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore-0.1.0-py3.6.egg/cryptostore/data/storage.py", line 36, in write
    s.write(exchange, data_type, pair, timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore-0.1.0-py3.6.egg/cryptostore/data/arctic.py", line 43, in write
    self.con[exchange].append(f"{data_type}-{pair}", df, upsert=True, chunk_size=chunk_size)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/chunkstore/chunkstore.py", line 523, in append
    self.__update(sym, item, metadata=metadata, combine_method=SER_MAP[sym[SERIALIZER]].combine, audit=audit)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/chunkstore/chunkstore.py", line 449, in __update
    data = SER_MAP[sym[SERIALIZER]].serialize(record)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 188, in serialize
    ret = self.converter.docify(df)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 124, in docify
    raise e
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 115, in docify
    arr, mask = self._convert_types(df[c].values)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/serialization/numpy_arrays.py", line 86, in _convert_types
    raise ValueError("Column of type 'mixed' cannot be converted to string")
ValueError: Column of type 'mixed' cannot be converted to string
```

**Comment by bmoscon** [comment]
some of the data types did change, before too many columns were being stored as strings, but this has since been fixed. There was also issues storing timestamps which has been fixed. You have to remove the arctic symbol, or pull the data into a dataframe, convert the column to a float, and the overwrite the data in arctic.

**Comment by nateGeorge** [comment]
Hmm, after a reboot it seems to be working.  Not quite sure why it stopped working originally.
