### ISSUE TITLE
Gemini works well in cryprofeed, while not in cryprostore

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#36]
config.yaml
```
exchanges:
    GEMINI:
        l2_book:
            symbols: [BTC-USD, ETH-USD, LTC-USD, ZEC-USD, BCH-USD, ETH-BTC, LTC-BTC, BCH-BTC]
            book_depth: 100
        trades: [BTC-USD, ETH-USD, LTC-USD, ZEC-USD, BCH-USD, ETH-BTC, LTC-BTC, BCH-BTC]
```

error message:
```
Process Collector-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/dong/.local/lib/python3.7/site-packages/cryptostore/collector.py", line 90, in run
    fh.add_feed(self.exchange, book_interval=window, config=self.exchange_config, callbacks=cb)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 83, in add_feed
    self._do_gemini_subscribe(feed, timeout, **kwargs)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 232, in _do_gemini_subscribe
    cb = {cb: deepcopy(feed.callbacks[cb]) for cb in cbs}
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 232, in <dictcomp>
    cb = {cb: deepcopy(feed.callbacks[cb]) for cb in cbs}
AttributeError: 'str' object has no attribute 'callbacks'
```

latest code of cryprofeed and cryprostore

**Comment by bmoscon** [comment]
fixed - thanks for raising the issue!
