### ISSUE TITLE
[ERROR] with BINANCE on 2019-08-26

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#40]
```bash
BINANCE:
        l2_book: 
            symbols: [ADA-BTC, ADA-ETH, ADA-USDT, ATOM-BTC, ATOM-USDC, ATOM-USDT, BCHABC-BTC, BNB-BTC, BNB-ETH, BNB-USDC, BNB-USDT, BTC-USDC, BTC-USDT, DASH-USDT,EOS-BTC, EOS-ETH, EOS-USDC, EOS-USDT, ETH-BTC, ETH-USDC, ETH-USDT, GNT-BTC, GNT-ETH, LTC-BTC, LTC-ETH, LTC-USDC, LTC-USDT, IOTA-USDT, NEO-USDT, QTUM-BTC, QTUM-ETH, QTUM-USDT, TRX-BTC, TRX-ETH, TRX-USDT, USDC-USDT, VET-ETH, VET-BTC, VET-USDT, XLM-BTC, XLM-ETH, XLM-USDC, XLM-USDT, XMR-USDT, XRP-BTC,
XRP-ETH, XRP-USDT, ZEC-USDT, ZRX-BTC, ZRX-ETH, ZRX-USDT, ONE-BTC, ONE-USDT]
            book_delta: true
            book_interval: 2000
        trades: [ADA-BTC, ADA-ETH, ADA-USDT, ATOM-BTC, ATOM-USDC, ATOM-USDT, BCHABC-BTC, BNB-BTC, BNB-ETH, BNB-USDC, BNB-USDT, BTC-USDC, BTC-USDT, DASH-USDT, EOS-BTC, EOS-ETH, EOS-USDC, EOS-USDT, ETH-BTC, ETH-USDC, ETH-USDT, GNT-BTC, GNT-ETH, LTC-BTC, LTC-ETH, LTC-USDC, LTC-USDT, IOTA-USDT, NEO-USDT, QTUM-BTC, QTUM-ETH, QTUM-USDT, TRX-BTC, TRX-ETH, TRX-USDT, USDC-USDT, VET-ETH, VET-BTC, VET-USDT, XLM-BTC, XLM-ETH, XLM-USDC, XLM-USDT, XMR-USDT, XRP-BTC,
XRP-ETH, XRP-USDT, ZEC-USDT, ZRX-BTC, ZRX-ETH, ZRX-USDT, ONE-BTC, ONE-USDT]
```

error msg:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/dong/.local/lib/python3.7/site-packages/cryptostore/collector.py", line 93, in run
    fh.add_feed(self.exchange, book_interval=window, config=self.exchange_config, callbacks=cb)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 83, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/exchange/binance.py", line 27, in __init__
    super().__init__(None, pairs=pairs, channels=channels, callbacks=callbacks, **kwargs)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 27, in __init__
    load_exchange_pair_mapping(self.id)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/standards.py", line 33, in load_exchange_pair_mapping
    mapping = gen_pairs(exchange)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/pairs.py", line 16, in gen_pairs
    return _exchange_function_map[exchange]()
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/pairs.py", line 22, in binance_pairs
    for symbol in pairs['symbols']:
KeyError: 'symbols'
```

The program runs well for 20 days. and crash today.
What I have done is update code to the latest version(both cryptostore and cryptofeed)

Also, other exchange runs well

**Comment by bmoscon** [comment]
this appears to be an intermittent issue, or perhaps your ip was banned - either way it means the REST api request to get the symbol mappings failed
