### ISSUE TITLE
AssertionError in /cryptostore/aggregator/aggregator.py

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#42]
```bash
2019-09-02 10:01:39,790 : ERROR : Aggregator running on PID 21035 died due to exception
Traceback (most recent call last):
  File "/home/dong/.local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 75, in loop
    assert(False)
AssertionError
Task exception was never retrieved
future: <Task finished coro=<Aggregator.loop() done, defined at /home/dong/.local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py:40> exception=AssertionError()>
Traceback (most recent call last):
  File "/home/dong/.local/lib/python3.7/site-packages/cryptostore/aggregator/aggregator.py", line 75, in loop
    assert(False)
AssertionError
```

**Comment by xiandong79** [comment]
try to fix it by https://github.com/bmoscon/cryptostore/pull/43

**Comment by bmoscon** [comment]
fixed/merged
