### ISSUE TITLE
Kraken Trades Data Issue

### ISSUE THREAD

**Issue by likso** [bmoscon/cryptostore#46]
The problem only on Kraken trades data. I had all other exchanges l2_book, trades and ticker setup and running without any problems. Using Redis as cache and Arctic as storage.

Try on both Ubuntu and Mac environment, same errors.

2019-11-27 18:28:54,194 : INFO : Starting cryptostore
2019-11-27 18:28:54,195 : INFO : Cryptostore running on PID 42159
2019-11-27 18:28:54,197 : INFO : Spawner started
2019-11-27 18:28:54,198 : INFO : Aggregator started
2019-11-27 18:28:54,199 : INFO : Spawner running on PID 42162
2019-11-27 18:28:54,200 : INFO : Cryptostore started
2019-11-27 18:28:54,200 : INFO : Aggregator running on PID 42163
2019-11-27 18:28:54,210 : INFO : start: ['KRAKEN'] stop: []
2019-11-27 18:28:54,211 : INFO : message: {"op": "start", "exchange": "KRAKEN", "collector": {"trades": ["BTC-USD"]}, "config": {"cache": "redis", "kafka": {"ip": "127.0.0.1", "port": 9092, "start_flush": true}, "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["arctic"], "pass_through": {"type": "zmq", "host": "127.0.0.1", "port": 5678}, "elastic": {"host": "http://127.0.0.1:9200", "user": null, "token": null, "shards": 10, "replicas": 0, "refresh_interval": "30s"}, "influx": {"host": "http://127.0.0.1:8086", "db": "example", "create": true}, "parquet": {"del_file": true, "S3": {"key_id": null, "secret": null, "bucket": null, "prefix": null}, "GCS": {"service_account": null, "bucket": null, "prefix": null}}, "arctic": "mongodb://127.0.0.1", "storage_interval": 60}}
2019-11-27 18:28:54,212 : INFO : Starting {'op': 'start', 'exchange': 'KRAKEN', 'collector': {'trades': ['BTC-USD']}, 'config': {'cache': 'redis', 'kafka': {'ip': '127.0.0.1', 'port': 9092, 'start_flush': True}, 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['arctic'], 'pass_through': {'type': 'zmq', 'host': '127.0.0.1', 'port': 5678}, 'elastic': {'host': 'http://127.0.0.1:9200', 'user': None, 'token': None, 'shards': 10, 'replicas': 0, 'refresh_interval': '30s'}, 'influx': {'host': 'http://127.0.0.1:8086', 'db': 'example', 'create': True}, 'parquet': {'del_file': True, 'S3': {'key_id': None, 'secret': None, 'bucket': None, 'prefix': None}, 'GCS': {'service_account': None, 'bucket': None, 'prefix': None}}, 'arctic': 'mongodb://127.0.0.1', 'storage_interval': 60}}
2019-11-27 18:28:54,216 : INFO : Collector for KRAKEN running on PID 42164
2019-11-27 18:28:54,220 : INFO : Flushing cache
/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/arctic/store/_pandas_ndarray_store.py:6: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import DataFrame, Series, Panel
2019-11-27 18:28:54,307 : INFO : Reading KRAKEN-trades-BTC-USD
2019-11-27 18:28:54,308 : INFO : No data for KRAKEN-trades-BTC-USD
2019-11-27 18:28:56,616 : ERROR : KRAKEN: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/exchange/kraken.py", line 125, in message_handler
    await self._trade(msg, self.channel_map[msg[0]][1])
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/exchange/kraken.py", line 70, in _trade
    timestamp=float(timestamp))
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 32, in __call__
    await self.write(feed, pair, timestamp, data)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 39, in write
    await self.redis.xadd(f"{self.key}-{feed}-{pair}", data)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/commands/streams.py", line 105, in xadd
    return self.execute(b'XADD', stream, *args)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/pool.py", line 195, in execute
    fut = conn.execute(command, *args, **kw)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/connection.py", line 323, in execute
    raise TypeError("args must not contain None")
TypeError: args must not contain None
2019-11-27 18:29:24,283 : ERROR : KRAKEN: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/exchange/kraken.py", line 125, in message_handler
    await self._trade(msg, self.channel_map[msg[0]][1])
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/exchange/kraken.py", line 70, in _trade
    timestamp=float(timestamp))
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 32, in __call__
    await self.write(feed, pair, timestamp, data)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 39, in write
    await self.redis.xadd(f"{self.key}-{feed}-{pair}", data)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/commands/streams.py", line 105, in xadd
    return self.execute(b'XADD', stream, *args)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/pool.py", line 195, in execute
    fut = conn.execute(command, *args, **kw)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/aioredis/connection.py", line 323, in execute
    raise TypeError("args must not contain None")
TypeError: args must not contain None

**Comment by bmoscon** [comment]
@likso thanks for the ticket. I'll look into this and get it fixed sometime this week

**Comment by bmoscon** [comment]
@likso fixed. you'll need to update both cryptofeed and cryptostore.

**Comment by likso** [comment]
@bmoscon Thanks for the quick fix. Confirm working.
