### ISSUE TITLE
Bybit Trades Read Error from Arctic

### ISSUE THREAD

**Issue by likso** [bmoscon/cryptostore#47]
The error comes from reading from Arctic, on Bybit trades data only. The error seems only happen with come chunks after 2019-11-29.

Running with latest cryptofeed and cryptostore.

```
conn = Arctic('mongodb://localhost')
lib = conn['BYBIT']
symbol = 'trades-BTC-USD'
lib.read(symbol, chunk_range=('2019-12-02 14:00:00', '2019-12-03 18:00:00'), filter_data=True)
```

```
Traceback (most recent call last):
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5167, in get_slice_bound
    return self._searchsorted_monotonic(label, side)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5128, in _searchsorted_monotonic
    raise ValueError("index must be monotonic increasing or decreasing")
ValueError: index must be monotonic increasing or decreasing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/likso/PycharmProjects/cryptofeed/arctic_test.py", line 48, in <module>
    main()
  File "/Users/likso/PycharmProjects/cryptofeed/arctic_test.py", line 38, in main
    df = lib.read(symbol, chunk_range=('2019-12-02 14:00:00', '2019-12-03 18:00:00'), filter_data=True)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/arctic/chunkstore/chunkstore.py", line 287, in read
    return deser(chunks[symbol[0]], **kwargs) if skip_filter else chunker.filter(deser(chunks[symbol[0]], **kwargs), chunk_range)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/arctic/chunkstore/date_chunker.py", line 122, in filter
    return data[start:end]
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2976, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 2358, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind="getitem")
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3216, in _convert_slice_indexer
    indexer = self.slice_indexer(start, stop, step, kind=kind)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 1151, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5034, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5248, in slice_locs
    start_slice = self.get_slice_bound(start, "left", kind)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5170, in get_slice_bound
    raise err
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5164, in get_slice_bound
    slc = self.get_loc(label)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 1039, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/Users/likso/PycharmProjects/cryptofeed/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 435, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 152, in pandas._libs.index.IndexEngine._get_loc_duplicates
  File "pandas/_libs/index_class_helper.pxi", line 122, in pandas._libs.index.Int64Engine._maybe_get_bool_indexer
KeyError: 1575295200000000000

Process finished with exit code 1
```

**Comment by bmoscon** [comment]
it looks like a timestamp is being written as a float as opposed to a timestamp. Can you read back the data in chunks (not using a chunk range, but using the chunkstore iterator) and see where the break happens? I'm guessing that the exchange changed their data format, but not sure, will have to look into it

**Comment by likso** [comment]
All chunks can be retrieved by iterator without any errors. I have two chunks between 2019-11-29 12:00:00 and 2019-11-29 14:00:00.

```
Chunk is: 
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 17825 entries, 2019-11-29 13:00:00 to 2019-11-29 13:59:58
Data columns (total 4 columns):
side     17825 non-null object
price    17825 non-null float64
id       17825 non-null object
size     17825 non-null float64
dtypes: float64(2), object(2)
memory usage: 696.3+ KB
                     side  ...     size
date                       ...         
2019-11-29 13:00:00  sell  ...     50.0
2019-11-29 13:00:01  sell  ...   9585.0
2019-11-29 13:00:01  sell  ...   4000.0
2019-11-29 13:00:01  sell  ...  42040.0
2019-11-29 13:00:01  sell  ...      7.0
...                   ...  ...      ...
2019-11-29 13:59:58   buy  ...   1217.0
2019-11-29 13:59:58   buy  ...   5712.0
2019-11-29 13:59:58   buy  ...   4115.0
2019-11-29 13:59:58  sell  ...    111.0
2019-11-29 13:59:58   buy  ...   1000.0

[17825 rows x 4 columns]
Chunk is: 
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 16499 entries, 2019-11-29 12:00:00 to 2019-11-29 12:59:59
Data columns (total 4 columns):
side     16499 non-null object
price    16499 non-null float64
id       16499 non-null object
size     16499 non-null float64
dtypes: float64(2), object(2)
memory usage: 644.5+ KB
                     side  ...     size
date                       ...         
2019-11-29 12:00:00  sell  ...  42600.0
2019-11-29 12:00:00   buy  ...    600.0
2019-11-29 12:00:02  sell  ...  18422.0
2019-11-29 12:00:02  sell  ...    500.0
2019-11-29 12:00:02   buy  ...      1.0
...                   ...  ...      ...
2019-11-29 12:59:58   buy  ...   1900.0
2019-11-29 12:59:59  sell  ...   1000.0
2019-11-29 12:59:59  sell  ...    500.0
2019-11-29 12:59:59   buy  ...   1296.0
2019-11-29 12:59:59  sell  ...   2047.0

[16499 rows x 4 columns]
```
It is bit strange that all of the below ranges can be retrieved without any problem.
```
    df = lib.read(symbol, chunk_range=('2019-11-29 12:00:00', '2019-11-29 13:59:00'), filter_data=True)
    df = lib.read(symbol, chunk_range=('2019-11-29 13:00:00', '2019-11-29 14:00:00'), filter_data=True)
    df = lib.read(symbol, chunk_range=('2019-11-29 13:59:00', '2019-11-29 14:00:00'), filter_data=True)
```

But this one below generate the errors.
```
df = lib.read(symbol, chunk_range=('2019-11-29 12:00:00', '2019-11-29 14:00:00'), filter_data=True)
```

**Comment by codesutras** [comment]
I'm facing the similar issue for versionStore as well. Is there any fix available to handle this issue ? All, what I'm doing is that every time, I have to re-generate the data from the date, where I've encountered issue.

Any thought  would be appreciated.

**Comment by pierson-we** [comment]
I've been getting the same error periodically when retrieving a chunk range of data. The indices that give rise to the error do not appear to be stored as strings and are indeed Timestamps from what I've been able to investigate. In investigating the index in the entire df (read without chunk_range), the index appeared to be out of order at some point. I confirmed that df.index.tolist() != list(sorted(df.index.tolist())). I reordered the index in proper sorted order and rewrote the df to Arctic and I didn't encounter the error again. Of note, I did not first check to see if simply rewriting the df to Arctic as is solved the issue so I can't say with 100% certainty it was due to the index order. I'll check this next time I encounter the issue.

I have since encountered the error and this workaround solved it temporarily, but with continued updating of the symbol in Arctic i've encountered the error again.

**Comment by pierson-we** [comment]
> I've been getting the same error periodically when retrieving a chunk range of data. The indices that give rise to the error do not appear to be stored as strings and are indeed Timestamps from what I've been able to investigate. In investigating the index in the entire df (read without chunk_range), the index appeared to be out of order at some point. I confirmed that df.index.tolist() != list(sorted(df.index.tolist())). I reordered the index in proper sorted order and rewrote the df to Arctic and I didn't encounter the error again. Of note, I did not first check to see if simply rewriting the df to Arctic as is solved the issue so I can't say with 100% certainty it was due to the index order. I'll check this next time I encounter the issue.
> 
> I have since encountered the error and this workaround solved it temporarily, but with continued updating of the symbol in Arctic i've encountered the error again.

I just realized that this isn't the Arctic github repository - I am not using cryptostore so I would think this is an Arctic issue.

**Comment by bmoscon** [comment]
This is an arctic issue - timestamps are not stored in sorted order
