### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptostore#58]
Hello! When I try to run cryptostore I get the following message. I searched through the issues and found a similar case, and it was solved by installing redis, but I already have it installed and configured. What could be the issue?

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/cryptostore", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cryptostore/bin/cryptostore.py", line 11, in main
    cs = Cryptostore(config=args.config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cryptostore/cryptostore.py", line 30, in __init__
    self.plugin.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cryptostore/plugin/controller.py", line 29, in start
    if 'plugins' in self.cfg:
TypeError: argument of type 'NoneType' is not iterable

**Comment by bmoscon** [comment]
that error looks like it cannot find a config file. an example config file is provided. Also python 3.6 is not supported. 3.7+ only.

**Comment by bmoscon** [comment]
Looking at the code though I'm not sure how you could ever get this error as the config loaders will emit errors if the config file doesnt exist or if the default doesnt exist. Try with 3.7+ and see if the error persists.

**Comment by rbdm-qnt** [comment]
Updated python and got it to work, thanks!
