### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by smatiush** [bmoscon/cryptostore#67]
hi,
i have a problem running cryptostore, this is the error from bash:

`root@bot1:~/cryptostore/cryptostore# cryptostore
Traceback (most recent call last):
  File "/usr/local/bin/cryptostore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/bin/cryptostore.py", line 11, in main
    cs = Cryptostore(config=args.config)
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/cryptostore.py", line 29, in __init__
    self.plugin = PluginController(config)
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/plugin/controller.py", line 26, in __init__
    self.cfg = Config(file_name)
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/config.py", line 37, in __init__
    self.config = AttrDict(yaml.load(fp, Loader=yaml.FullLoader))
AttributeError: module 'yaml' has no attribute 'FullLoader'`
The config file is located in the same folder of the executable.
when i put the `config.yaml` in the upper folder the problem change:
`  File "/usr/local/bin/cryptostore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/bin/cryptostore.py", line 11, in main
    cs = Cryptostore(config=args.config)
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/cryptostore.py", line 30, in __init__
    self.plugin.start()
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/plugin/controller.py", line 29, in start
    if 'plugins' in self.cfg:
TypeError: argument of type 'NoneType' is not iterable`
you now where the problem can be?

**Comment by vdbelt** [comment]
Which version of PyYAML are you running?

```python
> import yaml
> yaml.__version__
```

**Comment by smatiush** [comment]
`>>> import yaml
>>> yaml.__version__
'5.3'
`

**Comment by smatiush** [comment]
` import yaml
  >yaml.__version__
  >"5.3"`

**Comment by bmoscon** [comment]
Take a look at this:

https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

Seems to be some issue with the version of pyyaml you have installed, try updating it.

This is not a cryptostore issue though, so closing.
