### ISSUE TITLE
ERROR : COINBASE: encountered an exception, reconnecting

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#68]
```
2020-03-23 04:10:45,715 : ERROR : COINBASE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 201, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 230, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/exchange/coinbase.py", line 290, in message_handler
    await self._done(msg, timestamp)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/exchange/coinbase.py", line 242, in _done
    await self.book_callback(self.l3_book[pair], L3_BOOK, pair, False, delta, ts, timestamp)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 94, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp, receipt_timestamp=receipt_timestamp)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 112, in callback
    await cb(**kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 24, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/cryptofeed/backends/_util.py", line 16, in book_delta_convert
    data[side][convert(price)] = convert(amount)
TypeError: float() argument must be a string or a number, not 'dict'
```

**Comment by xiandong79** [comment]
```
COINBASE:
        retries: -1
        l3_book:
            symbols: [BTC-USD]
            max_depth: 300
            book_delta: true
            book_interval: 600
        trades: [BTC-USD]
        ticker: [BTC-USD]
```

**Comment by bmoscon** [comment]
I'll take a look. I dont think max_depth and delta are supported on L3 books, but I'd have to confirm.

**Comment by xiandong79** [comment]
max_depth and delta are supported on L3 books

**Comment by bmoscon** [comment]
@xiandong79 i saw you closed this, is this no longer an issue?

**Comment by xiandong79** [comment]
max_depth and delta are not supported on L3 books
the error disappears when I change it to L2 book.

Thanks
