### ISSUE TITLE
Fetching trade data with Huobi raises a KeyError: <class 'decimal.Decimal'>

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#95]
Hi,

When using following config file, I get the error below.

```yaml
cache: redis

redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    HUOBI:
        channel_timeouts:
            l2_book: 90
            trades: 90
            funding: 90
        retries: 6
        trades: [ADA-USDT]
```
(saving to Google Drive of course, no use to copy paste this section ;))

Here is the error I get (from `feedhandler.log`):
```bash
2020-08-18 21:55:06,861 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/util.py", line 35, in encode_command
    barg = _converters[type(arg)](arg)
KeyError: <class 'decimal.Decimal'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 213, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 242, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 87, in message_handler
    await self._trade(msg, timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 73, in _trade
    receipt_timestamp=timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 130, in callback
    await cb(**kwargs)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 33, in __call__
    await self.write(feed, pair, timestamp, receipt_timestamp, data)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 39, in write
    await self.redis.xadd(f"{self.key}-{feed}-{pair}", data)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/commands/streams.py", line 105, in xadd
    return self.execute(b'XADD', stream, *args)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/pool.py", line 196, in execute
    fut = conn.execute(command, *args, **kw)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/connection.py", line 351, in execute
    self._writer.write(encode_command(command, *args))
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/util.py", line 39, in encode_command
    " float, int, or str type".format(arg))
TypeError: Argument Decimal('10058811367582288561468103') expected to be of bytearray, bytes, float, int, or str type
2020-08-18 21:55:10,253 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/util.py", line 35, in encode_command
    barg = _converters[type(arg)](arg)
KeyError: <class 'decimal.Decimal'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 213, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 242, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 87, in message_handler
    await self._trade(msg, timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 73, in _trade
    receipt_timestamp=timestamp)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 130, in callback
    await cb(**kwargs)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 33, in __call__
    await self.write(feed, pair, timestamp, receipt_timestamp, data)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 39, in write
    await self.redis.xadd(f"{self.key}-{feed}-{pair}", data)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/commands/streams.py", line 105, in xadd
    return self.execute(b'XADD', stream, *args)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/pool.py", line 196, in execute
    fut = conn.execute(command, *args, **kw)
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/connection.py", line 351, in execute
    self._writer.write(encode_command(command, *args))
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/aioredis/util.py", line 39, in encode_command
    " float, int, or str type".format(arg))
TypeError: Argument Decimal('10058811367582288561468103') expected to be of bytearray, bytes, float, int, or str type
```

I have made a `pip install --upgrade` of cryptofeed and aioredis.
I have also pulled the last version of `cryptostore`, and installed it with `python setup.py install develop`.

Please, do you have any idea what could be the trouble?
Possibly a trouble directly in `cryptofeed`?
Thanks for your help!

**Comment by yohplala** [comment]
The error happens at the very start, while no data has been loaded yet, as stated by `cryptostore` logs:
```bash
2020-08-18 22:07:21,385 : INFO : Collector for HUOBI running on PID 6953
2020-08-18 22:07:21,389 : INFO : Flushing cache
2020-08-18 22:07:22,451 : INFO : Reading HUOBI-trades-ADA-USDT
2020-08-18 22:07:22,451 : INFO : No data for HUOBI-trades-ADA-USDT
2020-08-18 22:07:22,452 : INFO : Reading HUOBI-l2_book-ADA-USDT
2020-08-18 22:07:22,452 : INFO : No data for HUOBI-l2_book-ADA-USDT
2020-08-18 22:07:24,087 : ERROR : HUOBI: encountered an exception, reconnecting
```

**Comment by yohplala** [comment]
Ok, digging further, the error appears only when I retrieve trades, and does not appear if I retrieve only order books.
I am restricting the config file given above to only trade data.

**Comment by bmoscon** [comment]
fixed: https://github.com/bmoscon/cryptofeed/commit/b86407a04698fedbded281793b02c887ae307e13

**Comment by yohplala** [comment]
Thanks @bmoscon  wohaaa, that is fastsupport! :) Much appreciated!
