### ISSUE TITLE
Adding 'funding' & 'open_interest' to HUOBY_SWAP

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#96]
`funding` channel does not appear available for HUOBI_SWAP exchange, nor `open_interest`.
Following config...
```yaml
exchanges:
    HUOBI_SWAP:
        channel_timeouts:
            funding: 90
        retries: 6
        funding: [BTC-USD]
```
...raises following error:
```bash
2020-08-18 22:35:51,049 : INFO : No data for HUOBI_SWAP-funding-BTC-USD
Process Collector-1:1:
Traceback (most recent call last):
  File "/home/pierre/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/cryptostore-0.3.0-py3.7.egg/cryptostore/collector.py", line 113, in run
    fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 109, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi_swap.py", line 15, in __init__
    Feed.__init__(self, 'wss://api.hbdm.com/swap-ws', pairs=pairs, channels=channels, callbacks=callbacks, config=config, **kwargs)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 43, in __init__
    chan = feed_to_exchange(self.id, channel)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/standards.py", line 301, in feed_to_exchange
    ret = _feed_to_exchange_map[feed][exchange]
KeyError: 'HUOBI_SWAP'
```
Same with `open_interest`.

Please, is it possible to make them available?
Thanks

**Comment by bmoscon** [comment]
this belongs in cryptofeed, not here

**Comment by bmoscon** [comment]
see https://github.com/bmoscon/cryptofeed/issues/295

**Comment by bmoscon** [comment]
funding data now supported on huobi swap
