### ISSUE TITLE
Making error message linked to missing channels more understandable

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#97]
When a channel is missing for an exchange, the error message does not state which one.
If several channels are requested, this can be confusing.
Actually, when I got the message first, I thought that the exchange name itself was what was causing the trouble.

For instance `funding` channel does not appear available for HUOBI_SWAP exchange.
Following config...
```yaml
exchanges:
    HUOBI_SWAP:
        channel_timeouts:
            funding: 90
        retries: 6
        funding: [BTC-USD]
```
...raises following error:
```bash
Process Collector-1:1:
Traceback (most recent call last):
  File "/home/pierre/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/cryptostore-0.3.0-py3.7.egg/cryptostore/collector.py", line 113, in run
    fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 109, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/exchange/huobi_swap.py", line 15, in __init__
    Feed.__init__(self, 'wss://api.hbdm.com/swap-ws', pairs=pairs, channels=channels, callbacks=callbacks, config=config, **kwargs)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feed.py", line 43, in __init__
    chan = feed_to_exchange(self.id, channel)
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/standards.py", line 301, in feed_to_exchange
    ret = _feed_to_exchange_map[feed][exchange]
KeyError: 'HUOBI_SWAP'
```
The error message could state that `funding` is an unknown key.

**Comment by bmoscon** [comment]
fixed with https://github.com/bmoscon/cryptofeed/commit/e5c20cf69a2e93b2407f698a060029fb1a296bb8

**Comment by yohplala** [comment]
Thanks Bryant!
