### ISSUE TITLE
Fetching 'open_interest' in BINANCE_FUTURES raises websocket exceptions

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#98]
Following config...
```yaml
exchanges:
    BINANCE_FUTURES:
        channel_timeouts:
            open_interest: 90
        retries: 6
        open_interest: [BTC-USDT]
```
... raises following error.
```bash
2020-08-18 22:46:00,836 : ERROR : BINANCE_FUTURES: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 207, in _connect
    max_size=2**23, max_queue=None, origin=feed.origin) as websocket:
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400
2020-08-18 22:46:04,728 : ERROR : BINANCE_FUTURES: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 207, in _connect
    max_size=2**23, max_queue=None, origin=feed.origin) as websocket:
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/pierre/miniconda3/lib/python3.7/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400
```
I couldd check that it raises no trouble with `trades`, `l2_order_book` or `funding`.
Theoretically, if this channel is missing, my understanding is that a `KeyError` should be raised, as for instance reported in ticket #97 .

Reporting this error, but not sure abot the next step:
- either `open_interest` is a missing channel and there is a trouble in the fact that error messages are not consistent between different exchanges.
- or there is a specific trouble for channel with `BINANCE_FUTURES` exchange (a mapping trouble?)

Bests,

**Comment by bmoscon** [comment]
fixed on cryptpfeed 1.6.0 (unreleased, but in main branch on github)
